services:
  # MANDATORY SERVICES
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    secrets:
      - mariadb_root_password
      - mariadb_user_password
    volumes:
      - ${VOLUMES_ROOT}/db:/var/lib/mysql
    networks:
      - inception_net

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
    secrets:
      - mariadb_user_password
      - wp_manager_password
      - wp_editor_password
    volumes:
      - ${VOLUMES_ROOT}/wp:/var/www/html
    networks:
      - inception_net

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress

    ports:
      - "443:443"
    volumes:
      - ${VOLUMES_ROOT}/wp:/var/www/html
      - ${SECRETS_ROOT}/certs/frromero.42.fr.crt:/etc/ssl/certs/frromero.42.fr.crt:ro
      - ${SECRETS_ROOT}/certs/frromero.42.fr.key:/etc/ssl/private/frromero.42.fr.key:ro
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - inception_net

  # BONUS SERVICES
  web:
    build: ./requirements/bonus/web
    container_name: web
    restart: always
    profiles: [bonus]
    networks:
      - inception_net
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    restart: always
    profiles: [bonus]
    networks:
      - inception_net

volumes:
  db:
  wp:

networks:
  inception_net:
    driver: bridge

secrets:
  mariadb_root_password:
    file: ${PROJECT_ROOT}/secrets/mariadb_root_password.txt
  mariadb_user_password:
    file: ${PROJECT_ROOT}/secrets/mariadb_user_password.txt
  wp_manager_password:
    file: ${PROJECT_ROOT}/secrets/wp_manager_password.txt
  wp_editor_password:
    file: ${PROJECT_ROOT}/secrets/wp_editor_password.txt